version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Creating virtual environment for Prowler"
      - python -m venv prowler-venv
      - source prowler-venv/bin/activate
      - pip install --upgrade pip
      - pip install prowler==5.16.1
      - prowler --version

  pre_build:
    commands:
      - source prowler-venv/bin/activate
      - mkdir -p output

  build:
    commands:
      - source prowler-venv/bin/activate
      - prowler aws --compliance cis_1.2_aws --output-formats json-asff csv html --output-directory output 

artifacts:
  files:
    - 'output/**/*'
