version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install prowler
  pre_build:
    commands:
      - mkdir -p output
  build:
    commands:
      - prowler aws --compliance cis_1.5_aws --output-formats json,csv,html --output-directory output
artifacts:
  files:
    - 'output/**/*'
